export const boards = {
  // ========== a03 场景展板 (13条) ==========
  '3-1': { image: '/imgs/board/3-1.webp', text: '' },
  '3-2': {
    image: '/imgs/board/3-2.webp',
    text: 'Though Zhou Lu left us, his spirit shines forever like a star. The Vietnamese people built a monument in his memory, honoring this international hero from China.',
    title: 'Chapter 6: The Eternal Starlight',
    audio: ['/audio/6-chs.mp3', '/audio/6-eng.mp3', '/audio/6-tcw.mp3'],
  },
  '3-3': {
    image: '/imgs/board/3-3.webp',
    text: 'Though Zhou Lu left us, his spirit shines forever like a star. The Vietnamese people built a monument in his memory, honoring this international hero from China.',
    title: 'Chapter 6: The Eternal Starlight',
    audio: ['/audio/6-chs.mp3', '/audio/6-eng.mp3', '/audio/6-tcw.mp3'],
  },
  '3-4': { image: '/imgs/board/3-4.webp', text: '' },
  '3-5': { image: '/imgs/board/3-5.webp', text: '' },
  '3-6': { image: '/imgs/board/3-6.webp', text: '' },
  '3-7': { image: '/imgs/board/3-7.webp', text: '' },
  '3-8': { image: '/imgs/board/3-8.webp', text: '' },
  '3-9': { image: '/imgs/board/3-9.webp', text: '' },
  '3-10': { image: '/imgs/board/3-10.webp', text: '' },
  '3-11': { image: '/imgs/board/3-11.webp', text: '' },
  '3-12': { image: '/imgs/board/3-12.webp', text: '' },
  '3-13': {
    image: '/imgs/board/3-13.webp',
    text: "Look! This is the commemorative bronze statue of Martyr Zhou Lu! He loved studying from a young age, and his family supported him. His elder brothers protected him like big trees and helped him get into Hanshan Normal School, the best school in Chaoshan at that time – which is today's Hanshan Normal University. Going to school was no easy feat back then, and Zhou Lu was truly a \"good student\" in his village!",
    title: 'Chapter 1: The Book-Loving Youth',
    audio: ['/audio/1-chs.mp3', '/audio/1-eng.mp3', '/audio/1-tcw.mp3'],
  },

  // ========== a04 场景展板 (28条) ==========
  '2-1': { image: '/imgs/board/2-1.webp', text: '' },
  '2-2': { image: '/imgs/board/2-2.webp', text: '' },
  '2-3': { image: '/imgs/board/2-3.webp', text: '' },
  '2-4': { image: '/imgs/board/2-4.webp', text: '' },
  '2-5': { image: '/imgs/board/2-5.webp', text: '' },
  '2-6': { image: '/imgs/board/2-6.webp', text: '' },
  '2-7': { image: '/imgs/board/2-7.webp', text: '' },
  '2-8': {
    image: '/imgs/board/2-8.webp',
    text: "Deep in Huamei Mountain, there's a place called \"Cobra Cave\" –– it was the secret base of  Zhou Lu and his comrades! They held meetings, trained, and planned many brilliant operations there. Most impressively, they used their wisdom to seize weapons from the enemy and protect the common people!",
    title: 'Chapter 3: Secret Operations in the Cave',
    audio: ['/audio/3-chs.mp3', '/audio/3-eng.mp3', '/audio/3-tcw.mp3'],
  },
  '2-9': {
    image: '/imgs/board/2-9.webp',
    text: "Deep in Huamei Mountain, there's a place called \"Cobra Cave\" –– it was the secret base of  Zhou Lu and his comrades! They held meetings, trained, and planned many brilliant operations there. Most impressively, they used their wisdom to seize weapons from the enemy and protect the common people!",
    title: 'Chapter 3: Secret Operations in the Cave',
    audio: ['/audio/3-chs.mp3', '/audio/3-eng.mp3', '/audio/3-tcw.mp3'],
  },
  '2-10': { image: '/imgs/board/2-10.webp', text: '' },
  '2-11': { image: '/imgs/board/2-11.webp', text: '' },
  '2-12': {
    image: '/imgs/board/2-12.webp',
    text: 'In 1927, when the Red Army came to Chaoshan, Zhou Lu was only 19 years old. He and his classmates helped the wounded, using cloth from their school uniforms to bandage wounds. This experience strengthened his revolutionary beliefs even more!',
    title: 'Chapter 2: The "Seven-Day Red" of the Red Army',
    audio: ['/audio/2-chs.mp3', '/audio/2-eng.mp3', '/audio/2-tcw.mp3'],
  },
  '2-13': { image: '/imgs/board/2-13.webp', text: '' },
  '2-14': { image: '/imgs/board/2-14.webp', text: '' },
  '2-15': { image: '/imgs/board/2-15.webp', text: '' },
  '2-16': { image: '/imgs/board/2-16.webp', text: '' },
  '2-17': { image: '/imgs/board/2-17.webp', text: '' },
  '2-18': { image: '/imgs/board/2-18.webp', text: '' },
  '2-19': { image: '/imgs/board/2-19.webp', text: '' },
  '2-20': { image: '/imgs/board/2-20.webp', text: '' },
  '2-21': { image: '/imgs/board/2-21.webp', text: '' },
  '2-22': { image: '/imgs/board/2-22.webp', text: '' },
  '2-23': { image: '/imgs/board/2-23.webp', text: '' },
  '2-24': { image: '/imgs/board/2-24.webp', text: '' },
  '2-25': { image: '/imgs/board/2-25.webp', text: '' },
  '2-26': { image: '/imgs/board/2-26.webp', text: '' },
  '2-27': { image: '/imgs/board/2-27.webp', text: '' },
  '2-28': { image: '/imgs/board/2-28.webp', text: '' },

  // ========== a05 场景展板 (22条) ==========
  '1-1': { image: '/imgs/board/1-1.webp', text: '' },
  '1-2': {
    image: '/imgs/board/1-2.webp',
    text: 'In 1934, to escape the enemy,  Zhou Lu set off late at night, hid in the fishing nets of a boat, and sailed to Vietnam on a red-head boat. His family also moved secretly, and even the children at home became "little revolutionary fighters"!',
    title: 'Chapter 4: Adventures on the Red-Head Boat',
    audio: ['/audio/4-chs.mp3', '/audio/4-eng.mp3', '/audio/4-tcw.mp3'],
  },
  '1-3': { image: '/imgs/board/1-3.webp', text: '' },
  '1-4': {
    image: '/imgs/board/1-4.webp',
    text: 'In Vietnam, Zhou Lu took the alias "Zhou Xiangliang" and continued to fight for the revolution. He taught children to read, ran newspapers to spread revolutionary ideas. Unfortunately, he was later captured by the enemy, but he remained unyielding till the end, protecting revolutionary secrets with his life.',
    title: 'Chapter 5: Heroic Stories in Vietnam',
    audio: ['/audio/5-chs.mp3', '/audio/5-eng.mp3', '/audio/5-tcw.mp3'],
  },
  '1-5': {
    image: '/imgs/board/1-5.webp',
    text: 'In Vietnam, Zhou Lu took the alias "Zhou Xiangliang" and continued to fight for the revolution. He taught children to read, ran newspapers to spread revolutionary ideas. Unfortunately, he was later captured by the enemy, but he remained unyielding till the end, protecting revolutionary secrets with his life.',
    title: 'Chapter 5: Heroic Stories in Vietnam',
    audio: ['/audio/5-chs.mp3', '/audio/5-eng.mp3', '/audio/5-tcw.mp3'],
  },
  '1-6': { image: '/imgs/board/1-6.webp', text: '' },
  '1-7': { image: '/imgs/board/1-7.webp', text: '' },
  '1-8': { image: '/imgs/board/1-8.webp', text: '' },
  '1-9': { image: '/imgs/board/1-9.webp', text: '' },
  '1-10': { image: '/imgs/board/1-10.webp', text: '告华侨书' },
  '1-11': { image: '/imgs/board/1-11.webp', text: '' },
  '1-12': { image: '/imgs/board/1-12.webp', text: '' },
  '1-13': { image: '/imgs/board/1-13.webp', text: '' },
  '1-14': { image: '/imgs/board/1-14.webp', text: '' },
  '1-15': { image: '/imgs/board/1-15.webp', text: '' },
  '1-16': { image: '/imgs/board/1-16.webp', text: '' },
  '1-17': { image: '/imgs/board/1-17.webp', text: '' },
  '1-18': { image: '/imgs/board/1-18.webp', text: '' },
  '1-19': { image: '/imgs/board/1-19.webp', text: '' },
  '1-20': { image: '/imgs/board/1-20.webp', text: '' },
  '1-21': { image: '/imgs/board/1-21.webp', text: '' },
  '1-22': { image: '/imgs/board/1-22.webp', text: '' },
}
