export const scenes = {
  // ========== A区：凤园 ==========
  a00: {
    image: '/imgs/vr/a00.webp',
    hfov: 60,
    yaw: 70,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: -10, yaw: 70, target: 'a02' },
      { type: 'jump', pitch: 0, yaw: 175, target: 'b00' },
    ],
  },
  a02: {
    image: '/imgs/vr/a002.webp',
    hfov: 50,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: -10, yaw: 0, target: 'a03' },
      { type: 'jump', pitch: -10, yaw: -140, target: 'a00' },
    ],
  },
  a03: {
    image: '/imgs/vr/a03.webp',
    hfov: 50,
    sceneHfov: 45,
    yaw: -2,
    pitch: -3,
    hasBoards: true,
    hasFlower: true,
    hotSpots: [
      { type: 'board', pitch: 6, yaw: -130, boardId: '3-1' },
      { type: 'board', pitch: 6, yaw: -91, boardId: '3-2' },
      { type: 'board', pitch: 6, yaw: -78, boardId: '3-3' },
      { type: 'board', pitch: 6, yaw: -66, boardId: '3-4' },
      { type: 'board', pitch: 5.5, yaw: -57, boardId: '3-5' },
      { type: 'board', pitch: 5, yaw: -48, boardId: '3-6' },
      { type: 'board', pitch: 5.5, yaw: 40, boardId: '3-7' },
      { type: 'board', pitch: 6, yaw: 50, boardId: '3-8' },
      { type: 'board', pitch: 7, yaw: 62, boardId: '3-9' },
      { type: 'board', pitch: 7, yaw: 78, boardId: '3-10' },
      { type: 'board', pitch: 7, yaw: 95, boardId: '3-11' },
      { type: 'board', pitch: 6, yaw: 138, boardId: '3-12' },
      { type: 'board', pitch: 15, yaw: -3, boardId: '3-13' },
      { type: 'flower', pitch: -35, yaw: -3 },
      { type: 'jump', pitch: 5, yaw: -110, target: 'a05' },
      { type: 'jump', pitch: 5, yaw: 115, target: 'a04' },
      { type: 'jump', pitch: 6, yaw: -175, target: 'a02' },
      { type: 'jump', pitch: 0, yaw: 30, target: 'a06' },
    ],
  },
  a04: {
    image: '/imgs/vr/a04.webp',
    hfov: 50,
    sceneHfov: 90,
    yaw: -5,
    pitch: 0,
    hasBoards: true,
    hotSpots: [
      { type: 'board', pitch: 10, yaw: -111, boardId: '2-1' },
      { type: 'board', pitch: 10, yaw: -93, boardId: '2-2' },
      { type: 'board', pitch: 13, yaw: -78, boardId: '2-3' },
      { type: 'board', pitch: -2, yaw: -78, boardId: '2-4' },
      { type: 'board', pitch: -2, yaw: -66, boardId: '2-5' },
      { type: 'board', pitch: 13, yaw: -65, boardId: '2-6' },
      { type: 'board', pitch: -2, yaw: -55, boardId: '2-7' },
      { type: 'board', pitch: 8, yaw: -56, boardId: '2-8' },
      { type: 'board', pitch: 8, yaw: -48, boardId: '2-9' },
      { type: 'board', pitch: 8, yaw: -40, boardId: '2-10' },
      { type: 'board', pitch: 8, yaw: -30, boardId: '2-11' },
      { type: 'board', pitch: 8, yaw: -19, boardId: '2-12' },
      { type: 'board', pitch: 9, yaw: -8, boardId: '2-13' },
      { type: 'board', pitch: 8, yaw: 4, boardId: '2-14' },
      { type: 'board', pitch: 6, yaw: 16, boardId: '2-15' },
      { type: 'board', pitch: 6, yaw: 28, boardId: '2-16' },
      { type: 'board', pitch: 7, yaw: 37, boardId: '2-17' },
      { type: 'board', pitch: 8, yaw: 49, boardId: '2-18' },
      { type: 'board', pitch: -3, yaw: 77, boardId: '2-19' },
      { type: 'board', pitch: -5, yaw: 95, boardId: '2-20' },
      { type: 'board', pitch: 8, yaw: 122, boardId: '2-21' },
      { type: 'board', pitch: 7, yaw: 133, boardId: '2-22' },
      { type: 'board', pitch: 6, yaw: 141, boardId: '2-23' },
      { type: 'board', pitch: 9, yaw: 151, boardId: '2-24' },
      { type: 'board', pitch: 8, yaw: 160, boardId: '2-25' },
      { type: 'board', pitch: -8, yaw: -12, boardId: '2-26' },
      { type: 'board', pitch: -20, yaw: -5, boardId: '2-27' },
      { type: 'board', pitch: -20, yaw: -35, boardId: '2-28' },
      { type: 'jump', pitch: -5, yaw: -140, target: 'a03' },
    ],
  },
  a05: {
    image: '/imgs/vr/a05.webp',
    hfov: 50,
    sceneHfov: 45,
    yaw: 0,
    pitch: 0,
    hasBoards: true,
    hotSpots: [
      { type: 'board', pitch: 7, yaw: -158, boardId: '1-1' },
      { type: 'board', pitch: 7, yaw: -140, boardId: '1-2' },
      { type: 'board', pitch: 20, yaw: -140, boardId: '1-3' },
      { type: 'board', pitch: 8, yaw: -130, boardId: '1-4' },
      { type: 'board', pitch: 9, yaw: -118, boardId: '1-5' },
      { type: 'board', pitch: 8, yaw: -53, boardId: '1-6' },
      { type: 'board', pitch: 7, yaw: -42, boardId: '1-7' },
      { type: 'board', pitch: 6.5, yaw: -35, boardId: '1-8' },
      { type: 'board', pitch: 6, yaw: -21, boardId: '1-9' },
      { type: 'board', pitch: 7, yaw: -3, boardId: '1-10' },
      { type: 'board', pitch: 7, yaw: 17, boardId: '1-11' },
      { type: 'board', pitch: 9, yaw: 31, boardId: '1-12' },
      { type: 'board', pitch: 8, yaw: 39, boardId: '1-13' },
      { type: 'board', pitch: 9, yaw: 50, boardId: '1-14' },
      { type: 'board', pitch: 10, yaw: 65, boardId: '1-15' },
      { type: 'board', pitch: 10, yaw: 88, boardId: '1-16' },
      { type: 'board', pitch: 10, yaw: 110, boardId: '1-17' },
      { type: 'board', pitch: -8, yaw: -16, boardId: '1-18' },
      { type: 'board', pitch: -8, yaw: 8, boardId: '1-19' },
      { type: 'board', pitch: -8, yaw: 0, boardId: '1-20' },
      { type: 'board', pitch: -8, yaw: -8, boardId: '1-21' },
      { type: 'board', pitch: -20, yaw: -3, boardId: '1-22' },
      { type: 'jump', pitch: -5, yaw: 138, target: 'a03' },
    ],
  },
  a06: {
    image: '/imgs/vr/a06.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: 45, yaw: 0, target: 'a09' },
      { type: 'jump', pitch: 0, yaw: -115, target: 'a03', spotClass: 'huge' },
    ],
  },
  a09: {
    image: '/imgs/vr/a09.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hasNoneSpots: true,
    hotSpots: [
      { type: 'jump', pitch: 0, yaw: -35, target: 'a06' },
      { type: 'none', pitch: 0, yaw: 115 },
      { type: 'none', pitch: 2, yaw: -110 },
      { type: 'jump', pitch: 0, yaw: 180, target: 'a12' },
    ],
  },
  a11: {
    image: '/imgs/vr/a11.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: 5, yaw: -35, target: 'a12' },
      { type: 'jump', pitch: 60, yaw: 160, target: 'a15' },
    ],
  },
  a12: {
    image: '/imgs/vr/a12.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: 0, yaw: 95, target: 'a11' },
      { type: 'jump', pitch: 0, yaw: 180, target: 'a09' },
    ],
  },
  a15: {
    image: '/imgs/vr/a15.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: -70, yaw: -100, target: 'a11' },
    ],
  },

  // ========== B区：至德堂 ==========
  b00: {
    image: '/imgs/vr/b00.webp',
    hfov: 45,
    yaw: -120,
    pitch: -5,
    hotSpots: [
      { type: 'jump', pitch: 0, yaw: -25, target: 'a02' },
      { type: 'jump', pitch: -5, yaw: -120, target: 'b01-1' },
    ],
  },
  'b01-1': {
    image: '/imgs/vr/b01-1.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: -5, yaw: 160, target: 'b00' },
      { type: 'jump', pitch: -5, yaw: 100, target: 'b04' },
      { type: 'jump', pitch: -5, yaw: 210, target: 'b05' },
      { type: 'jump', pitch: -5, yaw: -40, target: 'b01-2' },
    ],
  },
  'b01-2': {
    image: '/imgs/vr/b01-2.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: -10, yaw: 178, target: 'b01-1', spotClass: 'huge', spotColor: 'gray' },
      { type: 'jump', pitch: -10, yaw: 0, target: 'b02-1', spotClass: 'huge', spotColor: 'gray' },
    ],
  },
  'b02-1': {
    image: '/imgs/vr/b02-1.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: -10, yaw: -35, target: 'b01-2' },
      { type: 'jump', pitch: -5, yaw: 55, target: 'b02-2' },
    ],
  },
  'b02-2': {
    image: '/imgs/vr/b02-2.webp',
    hfov: 45,
    yaw: -90,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: 0, yaw: 180, target: 'b02-1' },
      { type: 'jump', pitch: 0, yaw: -90, target: 'c00' },
    ],
  },
  b04: {
    image: '/imgs/vr/b04.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: 0, yaw: 180, target: 'b05' },
      { type: 'jump', pitch: 0, yaw: 135, target: 'b00' },
    ],
  },
  b05: {
    image: '/imgs/vr/b05.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: 180, yaw: 0, target: 'b04' },
      { type: 'jump', pitch: 0, yaw: -140, target: 'b00' },
      { type: 'jump', pitch: 0, yaw: 165, target: 'b01-1' },
    ],
  },

  // ========== C区：易安精舍 ==========
  c00: {
    image: '/imgs/vr/c00.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: 0, yaw: 0, target: 'c04' },
    ],
  },
  c01: {
    image: '/imgs/vr/c01.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: -5, yaw: 50, target: 'b02-2' },
      { type: 'jump', pitch: 0, yaw: 0, target: 'c04' },
      { type: 'jump', pitch: -5, yaw: -65, target: 'c02' },
      { type: 'jump', pitch: -5, yaw: 70, target: 'c03' },
    ],
  },
  c02: {
    image: '/imgs/vr/c02.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: -5, yaw: -40, target: 'c01', spotColor: 'black' },
    ],
  },
  c03: {
    image: '/imgs/vr/c03.webp',
    hfov: 45,
    yaw: 0,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: 0, yaw: 12, target: 'c01', spotColor: 'black' },
    ],
  },
  c04: {
    image: '/imgs/vr/c04.webp',
    hfov: 60,
    yaw: 170,
    pitch: 0,
    hotSpots: [
      { type: 'jump', pitch: 0, yaw: 100, target: 'c00' },
      { type: 'jump', pitch: 0, yaw: -70, target: 'b02-2' },
      { type: 'jump', pitch: 0, yaw: 155, target: 'c03' },
      { type: 'jump', pitch: 0, yaw: -130, target: 'c02' },
    ],
  },
}
